# Copyright (c) 2016 Alex Kramer <kramer.alex.kramer@gmail.com>
# See the LICENSE.txt file at the top-level directory of this distribution.

Import("env")

env.Library("wfmath", source=Glob("*.f90"))
